name: Deploy Backup - Dev
on:
  push:
    branches:
      - dev
jobs:
  jenkinsJob:
    name: Deploy Backup
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backup start job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "opex-backup-dev"